---
- name: Reload postgresql service
  ansible.builtin.systemd_service:
    name: postgresql.service
    state: reloaded
  ignore_errors: '{{ ansible_check_mode }}'

- name: Restart zabbix-server service
  ansible.builtin.systemd_service:
    name: zabbix-server.service
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'

- name: Reload nginx service
  ansible.builtin.systemd_service:
    name: nginx.service
    state: reloaded
  ignore_errors: '{{ ansible_check_mode }}'
