---
- name: Check if grafana is installed
  ansible.builtin.stat:
    path: /usr/sbin/grafana-server
  changed_when: false
  check_mode: false
  register: grafana_is_installed

- name: Check current grafana version
  ansible.builtin.command: /usr/sbin/grafana-server --version
  changed_when: false
  failed_when: false
  check_mode: false
  when: grafana_is_installed.stat.exists
  register: grafana_current_version

- name: Install grafana package
  ansible.builtin.dnf:
    name: '{{ grafana_download_url }}'
    disable_gpg_check: true
    state: present
  when: not grafana_is_installed.stat.exists
    or grafana_version not in grafana_current_version.stdout_lines | first

# На RHEL9 невозможно запустить Grafana с ошибкой:
# Synchronizing state of grafana-server.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
# Executing: /usr/lib/systemd/systemd-sysv-install enable grafana-server
# Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory
- name: Remove grafana init script
  ansible.builtin.file:
    path: /etc/rc.d/init.d/grafana-server
    state: absent

- name: Update grafana certificate file
  ansible.builtin.copy:
    content: |
      {{ lookup('ansible.builtin.file', tls_cert_cert) }}
      {{ lookup('ansible.builtin.file', tls_ca_cert) }}
    dest: /etc/grafana/host.crt
    backup: true
    owner: root
    group: root
    mode: '0644'
  diff: false
  notify: Restart grafana-server service

- name: Update grafana key file
  ansible.builtin.copy:
    src: '{{ tls_cert_key }}'
    dest: /etc/grafana/host.key
    backup: true
    owner: grafana
    group: grafana
    mode: '0640'
  no_log: true
  notify: Restart grafana-server service

- name: Update grafana config
  ansible.builtin.template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
    backup: true
    owner: root
    group: grafana
    mode: '0640'
  no_log: true
  notify: Restart grafana-server service

- name: Enable and start grafana-server service
  ansible.builtin.systemd:
    name: grafana-server.service
    enabled: true
    daemon_reload: true
    state: started
  when: not ansible_check_mode
