---
- name: Create host private key
  delegate_to: localhost
  become: false
  community.crypto.openssl_privatekey:
    path: '{{ tls_cert_key }}'
  no_log: true

- name: Create host certificate signing request (CSR)
  delegate_to: localhost
  become: false
  community.crypto.openssl_csr_pipe:
    common_name: '{{ tls_cert_cn }}'
    subject_alt_name: '{{ tls_cert_san }}'
    use_common_name_for_san: false
    privatekey_path: '{{ tls_cert_key }}'
  no_log: true
  changed_when: false
  register: csr

- name: Create host certificate from CSR
  delegate_to: localhost
  become: false
  community.crypto.x509_certificate:
    path: '{{ tls_cert_cert }}'
    csr_content: '{{ csr.csr }}'
    provider: ownca
    ownca_path: '{{ tls_cert_ca_cert }}'
    ownca_privatekey_path: '{{ tls_cert_ca_key }}'
    ownca_not_after: '{{ tls_cert_not_after }}'
    ownca_not_before: '-1d'
  no_log: true
