---
internal_ip: 192.168.50.20

prometheus_version: 3.0.0-beta.0
prometheus_download_url: "https://github.com/prometheus/prometheus/releases\
  /download/v{{ prometheus_version }}\
  /prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_password: '{{ lookup("ansible.builtin.password",
  "passwords/prometheus.txt", length=32) }}'
prometheus_password_hash: '{{ lookup("ansible.builtin.password",
  "passwords/prometheus.txt", length=32, encrypt="bcrypt", ident="2y") }}'

prometheus_retention_time: 15d
prometheus_retention_size: 10GB

grafana_version: '11.2.1'
grafana_subver: '-1'
grafana_download_url: "https://dl.grafana.com/oss/release/\
  grafana-{{ grafana_version }}{{ grafana_subver }}.x86_64.rpm"

grafana_admin_user: otus
grafana_admin_password: '{{ lookup("ansible.builtin.password",
  "passwords/grafana_admin.txt", length=32) }}'
