---
- name: Update zabbix-server CA file
  ansible.builtin.copy:
    src: '{{ tls_ca_cert }}'
    dest: /etc/zabbix/zabbix_ca.crt
    backup: true
    owner: zabbix
    group: zabbix
    mode: '0644'
  diff: false
  notify: Restart zabbix-server service

- name: Update zabbix-server certificate file
  ansible.builtin.copy:
    src: '{{ tls_zabbix_server_cert }}'
    dest: /etc/zabbix/zabbix_server.crt
    backup: true
    owner: zabbix
    group: zabbix
    mode: '0644'
  diff: false
  notify: Restart zabbix-server service

- name: Update zabbix-server key file
  ansible.builtin.copy:
    src: '{{ tls_zabbix_server_key }}'
    dest: /etc/zabbix/zabbix_server.key
    backup: true
    owner: zabbix
    group: zabbix
    mode: '0600'
  no_log: true
  notify: Restart zabbix-server service

- name: Configure zabbix-server
  ansible.builtin.template:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    backup: true
    owner: root
    group: zabbix
    mode: '0600'
    validate: zabbix_server --test-config --config %s
  no_log: true
  notify: Restart zabbix-server service

- name: Configure zabbix gui
  ansible.builtin.template:
    src: zabbix.conf.php
    dest: /etc/zabbix/web/zabbix.conf.php
    backup: true
    owner: apache
    group: apache
    mode: '0600'
  no_log: true

- name: Enable and start zabbix-server service
  ansible.builtin.systemd_service:
    name: zabbix-server.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
