---
global:
  scrape_interval: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
    basic_auth:
      username: prometheus
      password_file: /etc/prometheus/prometheus.passwd
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
    basic_auth:
      username: metrics
      password_file: /etc/prometheus/metrics.passwd
    static_configs:
{% for host in groups['all'] %}
      - targets:
          - '{{ hostvars[host].internal_ip }}:9100'
      - labels:
          instance: '{{ host }}'
{% endfor %}
